<?php include('blocks/head.phtml'); ?>

<div class="jumbotron">
    <h1>L.A.M.P. - GOC 2017</h1>
    <p>Augmented Reality Challenge</p>
</div>

<ul class="nav nav-pills nav-stacked">
    <li role="presentation"><a href="/quest-create">Create</a></li>
    <li role="presentation"><a href="/quest-list">List</a></li>
    <li role="presentation"><a href="/achievements">Achievements</a></li>
</ul>

<?php include('blocks/foot.phtml'); ?>
