<?php include('blocks/head.phtml'); ?>

        <h1>LAMP GOC 2017</h1>
        <div>challange accepted!</div>

<button onclick="getLocation()">Try It</button>

Place: <p id="demo"></p>

<script>
    var x = document.getElementById("demo");

    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }

    function showPosition(position) {
        x.innerHTML = "Latitude: " + position.coords.latitude +
            "<br>Longitude: " + position.coords.longitude;
    }
</script>


<?php include('blocks/foot.phtml'); ?>
