<?php include('blocks/head.phtml'); ?>

<form class="form-horizontal">
    <fieldset>

        <input type="hidden" id="longitude" name="longitude" value="" />
        <input type="hidden" id="latitude" name="latitude" value="" />

        <!-- Form Name -->
        <legend>Create quest</legend>

        <!-- Longitude -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="coordinates">Coordinates</label>
            <div class="col-md-4">
                <input id="coordinates" name="coordinates" type="text" class="form-control input-md" readonly="readonly" value="" />

            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="name">Name</label>
            <div class="col-md-4">
                <input id="name" name="name" type="text" placeholder="quest name" class="form-control input-md" required="">

            </div>
        </div>

        <!-- Textarea -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="description">Description</label>
            <div class="col-md-4">
                <textarea class="form-control" id="description" name="description">quest description</textarea>
            </div>
        </div>

        <!-- Text input-->
        <div class="form-group">
            <label class="col-md-4 control-label" for="experience_point">XP</label>
            <div class="col-md-4">
                <input id="experience_point" name="experience_point" type="text" placeholder="experience points" class="form-control input-md" required="">

            </div>
        </div>

        <!-- Button -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="send"></label>
            <div class="col-md-4">
                <button id="send" name="send" class="btn btn-primary">Create quest</button>
            </div>
        </div>

    </fieldset>
</form>


<script>
    getLocation();
</script>

<?php include('blocks/foot.phtml'); ?>
